# fly.toml app configuration file generated for radix-vaults-client on 2026-03-17T09:24:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'radix-vaults-client'
primary_region = 'ams'

[build]
  dockerfile = 'dockerfiles/client.Dockerfile'

  [build.args]
    VITE_API_BASE_URL = 'https://radix-vaults-server.fly.dev'
    VITE_DAPP_DEFINITION_ADDRESS = 'account_tdx_2_1c84d22un4jrfgwthrwkagfceppmg62c99dxey7u9vmv67s9ahvw6kn'
    VITE_ENV = 'prod'
    VITE_NETWORK_ID = '2'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
