/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsAddRouteImport } from './routes/vaults.add'
import { Route as VaultsVaultIdRouteImport } from './routes/vaults.$vaultId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsAddRoute = VaultsAddRouteImport.update({
  id: '/vaults/add',
  path: '/vaults/add',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsVaultIdRoute = VaultsVaultIdRouteImport.update({
  id: '/vaults/$vaultId',
  path: '/vaults/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/vaults/add': typeof VaultsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/vaults/add': typeof VaultsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/vaults/add': typeof VaultsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/team' | '/vaults/$vaultId' | '/vaults/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/team' | '/vaults/$vaultId' | '/vaults/add'
  id: '__root__' | '/' | '/team' | '/vaults/$vaultId' | '/vaults/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamRoute: typeof TeamRoute
  VaultsVaultIdRoute: typeof VaultsVaultIdRoute
  VaultsAddRoute: typeof VaultsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/add': {
      id: '/vaults/add'
      path: '/vaults/add'
      fullPath: '/vaults/add'
      preLoaderRoute: typeof VaultsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$vaultId': {
      id: '/vaults/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof VaultsVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamRoute: TeamRoute,
  VaultsVaultIdRoute: VaultsVaultIdRoute,
  VaultsAddRoute: VaultsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
